### PR TITLE
Add a 'branch_only' parameter for /module

### PR DESCRIPTION
**Pull request by raincz**
When passing this parameter, it tries to detect the branch from the module as well and apply it using the -e parameter to r10k. For modules that are branch-linked with the main repository, this will trigger an update *only* to the respective environment, rather than all environments.

* For pushes into a branch of the module corresponding to an environment, this merely saves processing time.
* For pushes to the default branch (of the module) which would affect all environments, this will block updates to all environments except for the default one (ie. production). This helps prevent unsolicited updates of an environment that could break it, until the environment itself is updated by other means (eg. by pushing into the respective branch of the source repository or module).

### CODE REVIEW

**Comment by raincz** [comment]
This addresses issue https://github.com/voxpupuli/webhook-go/issues/133 as described.

**Comment by raincz** [comment]
(sorry, missed the notification) It comes from the URL. ie `http://<host:port>/api/v1/r10k/module?branch_only=1`

**Comment by raincz** [comment]
A personal note to our use case: Gitlab (or any other git manager for that matter) doesn't really understand your puppet structure, or which repository is base puppet and which is a module. But they usually have the webhooks configured on a per-repository basis, so it makes sense that you would have the ability to distinguish/force this sort of stuff directly in a particular webhook URL. You already have to switch between `api/.../environment` and `api/.../module` anyway, so adding other context-dependent options was the most logical implementation for me.

**Comment by raincz** [comment]
Hello @dhollinger , is there anything else I should do for this? Any issues with the patch I should fix?

**Comment by dhollinger** [comment]
I have to look into why it isn't letting me merge. The GitHub Android app isn't clear on the reason. I'll take a look at it a little later today. If I get it fixed, I can get it merged

**Comment by raincz** [comment]
Thanks!

**Pull request merged**
